### ISSUE TITLE
Change the python tooling used in the project

### ISSUE THREAD

**Issue by yacoob** [jmgilman/beancount-stubs#12]
I'd like to switch the following:

- poetry to rye
- mypy to basedpyright
- black to ruff
- flake8 to ruff

The primary rationale is that it's what I'm used to :) It'll be bit faster to operate too. Last but not least, rye uses standard dependency table in `pyproject.toml`, as compared to poetry's custom one.

@jmgilman, let me know if you're OK with this - I'll stick to what's currently set up.

**Comment by jmgilman** [comment]
Fine with me. What you suggested is what I use in my more recent projects. This one is a bit outdated :)

**Comment by yacoob** [comment]
Completed via 587299485c8dea3f6ef5267d4910775ffc1ec01f.
