### ISSUE TITLE
Argument 6/7 to "Transaction" has incompatible type "frozenset[Any]"; expected "set[Any] | None"

### ISSUE THREAD

**Issue by valpackett** [jmgilman/beancount-stubs#4]
This happens when passing the `beancount.core.data.EMPTY_SET`.

`None` should **not** be allowed here, actually, because:

```
AssertionError: Invalid tags type: <class 'NoneType'>
```

**Comment by yacoob** [comment]
fixed by https://github.com/jmgilman/beancount-stubs/pull/10
